# Build Stage
FROM node:18-alpine as build
WORKDIR /app
COPY dashboard/react/package.json dashboard/react/package-lock.json ./
RUN npm install
COPY dashboard/react/ .
ARG REACT_APP_API_URL=http://localhost:8000
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY dashboard/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]